apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-Deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: rajsingh8826/myapp
          ports:
            - containerPort: 5000
            
        